config/routes.rb
Rails.application.routes.draw do
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  def index
  end

  def new
  	@post = Post.new(post_params)
	if @post.save
  	  redirect_to @post  		
  	end  
  end
  
  def post_params
  	params.require(:post).permit(:title, :content)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>new post</h1>

<%= form_for @post do |f| %>
	<p>
	<%= f.label :title %>
	<%= f.text_area :title %>
	</p>
	<br>
	<p>
	<%= f.label :content %>
	<%= f.text_area :content %>
	</p>
	<%= f.submit %>
<% end %>
<br>
<%= link_to "All Post", posts_index_path %>